name: Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: 1arp/create-a-file-action@0.2
      with:
        #path: 'src'
        file: 'Dockerfile'
        content: |
          # Container image that runs your code
          FROM mcr.microsoft.com/windows/servercore:ltsc2019
          # Copies your code file from your action repository to the filesystem path `/` of the container
          COPY entrypoint.sh /entrypoint.sh
          # Code file to execute when the docker container starts up (`entrypoint.sh`)
          ENTRYPOINT ["/entrypoint.sh"]
          
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{github.workspace}}
      
    - run: |
        echo '\# Container image that runs your code \n FROM mcr.microsoft.com/windows/servercore:ltsc2019 \n \# Copies your code file from your action repository to the filesystem path \`/\` of the container \n COPY entrypoint.sh /entrypoint.sh \n \# Code file to execute when the docker container starts up (\`entrypoint.sh\`) \n ENTRYPOINT \[\"/entrypoint.sh\"\]'
          
    - name: executing a docker command from the command line!
      run: |
        curl ${{ github.workspace }}/Dockerfile | docker build -f - .
        
#     - uses: '${{ github.workspace }}/action.yml'
#       with:
#         who-to-greet: 'Mona the Octocat'

    - run: |
        docker images
